[tasks.install-hooks]
script = '''
echo "Installing git hooks..."
cp .githooks/* .git/hooks
'''
script_runner = "@shell"

[tasks.pre-coverage]
install_crate = "cargo-nextest"

[tasks.coverage]
script = '''
cargo llvm-cov test --all-features --lcov --ignore-filename-regex ".cargo|.*_test\.rs" > ./target/debug/lcov.info
genhtml -o ./target/debug/coverage/ --show-details --ignore-errors source --legend ./target/debug/lcov.info
'''
clear = true
install_crate = { binary = "cargo-llvm-cov", rustup_component_name = "llvm-tools-preview" }
dependencies = ["pre-coverage"]

[tasks.view-coverage]
script = '''
xdg-open ./target/debug/coverage/index.html
'''
dependencies = ["coverage"]

[tasks.view-coverage.windows]
script = '''
./target/debug/coverage/index.html
'''
dependencies = ["coverage"]
script_runner = "@shell"

[tasks.test]
command = "cargo"
args = ["test", "--all-features"]
clear = true
install_crate = "cargo-nextest"

[tasks.test-docs]
command = "cargo"
args = ["test", "--doc", "--all-features"]


[tasks.open-docs]
env = { RUSTDOCFLAGS = "--cfg docsrs -D warnings" }
toolchain = "nightly"
command = "cargo"
args = [
    "doc",
    "-Zunstable-options",
    "-Zrustdoc-scrape-examples",
    "--all-features",
    "--no-deps",
    "--open",
]

[tasks.watch-docs]
env = { RUSTDOCFLAGS = "--cfg docsrs -D warnings" }
command = "watchexec"
args = [
    "-r",
    "-e",
    "rs,md",
    "--",
    "cargo",
    "+nightly",
    "doc",
    "-Zunstable-options",
    "-Zrustdoc-scrape-examples",
    "--all-features",
    "--no-deps",
]
install_crate = "watchexec-cli"

[tasks.build-all]
command = "cargo"
args = ["build", "--all-features", "--examples"]

[tasks.min-versions]
command = "cargo"
install_crate = "cargo-minimal-versions"
args = ["minimal-versions", "check", "--all-features", "--direct"]
